### ISSUE TITLE
疑似，11.1后破解防沉迷失效？

### ISSUE THREAD

**Issue by Alkaid-Star** [Dr-WeiAL/ArkNightsForMinor#3]
如题，感谢您在之前的日子里作出的贡献。
但是11月1日后方舟进行大更新需要重新下载客户端。
据说是提升了反破解防沉迷的手段。。
请问这个项目还能继续做下去破解防沉迷么
如果可以的话请尽快发布最新版安装包QAQ
谢谢啦！

**Comment by Dr-WeiAL** [comment]
作者都删库了，如果目前的方法不能用那也没办法了，因为之前因为破解防沉迷会导致一些利益问题，所以才修了吧

**Comment by Alkaid-Star** [comment]
唉，希望能有其他方法吧。
早知道就用其他人身份证了。。。

**Comment by luanmouren** [comment]
草了，有人搞出来新方法麻烦踢我一脚:(

**Comment by Rain0Jack** [comment]
关于yj更新个fcm炸出来多少人这档事

**Comment by Dr-WeiAL** [comment]
刚编译了一个试了下，提示信息不是防沉迷内容，估计是又加了一层验证，绕过了第一层没绕过第二层，如果yj那边第二层改成了服务器验证那估计就没办法了(

**Comment by Rain0Jack** [comment]
> 刚编译了一个试了下，提示信息不是防沉迷内容，估计是又加了一层验证，绕过了第一层没绕过第二层，如果yj那边第二层改成了服务器验证那估计就没办法了(

艹了，大号估计要废

**Comment by Aqua0v0** [comment]
刚刚试了一下，老办法确实不行了，大佬等你更新了T-T

**Comment by Alkaid-Star** [comment]
好家伙，加油！
我也蹲github（

**Comment by YYJ114514** [comment]
搞定了踢我一脚，最好能把安装包发出来吧，未成年太痛苦了

**Comment by Yingqidaoge** [comment]
今天就蹲这了

**Comment by Kamui233** [comment]
就是说明天4:00前有机会吗，大佬加油呜，能蹲到吗呜

**Comment by Rain0Jack** [comment]
> 就是说明天4:00前有机会吗，大佬加油呜，能蹲到吗呜

大概率没机会了，这个大佬已经跑了，还有一个打算明天研究

**Comment by Kamui233** [comment]
不是吧😭难道要回到三小时了吗😭

**Comment by lingranw** [comment]
> 作者都删库了，如果目前的方法不能用那也没办法了，之前因为破解防沉迷会导致一些利益问题，所以才修了吧

那个润！的文件有什么用吗

**Comment by Dr-WeiAL** [comment]
> > 作者都删库了，如果目前的方法不能用那也没办法了，之前因为破解防沉迷会导致一些利益问题，所以才修了吧
> 
> 那个润！的文件有什么用吗

我把文件都删了，剩下的那个就是你们看到的主页（

**Comment by Kamui233** [comment]
> > > 作者都删库了，如果目前的方法不能用那也没办法了，之前因为破解防沉迷会导致一些利益问题，所以才修了吧
> > 
> > 
> > 那个润！的文件有什么用吗
> 
> 我把文件都删了，剩下的那个就是你们看到的主页（

所以说基本上这个项目算是结束了？

**Comment by Rain0Jack** [comment]
https://github.com/FCMRIP/HK-Arknights/issues/10#issuecomment-956311693
隔壁的结果

**Comment by Dr-WeiAL** [comment]
> > > > 作者都删库了，如果目前的方法不能用那也没办法了，之前因为破解防沉迷会导致一些利益问题，所以才修了吧
> > > 
> > > 
> > > 那个润！的文件有什么用吗
> > 
> > 
> > 我把文件都删了，剩下的那个就是你们看到的主页（
> 
> 所以说基本上这个项目算是结束了？

算是吧，毕竟我也不是作者，只是作者把库删了后我就成了某一个源头了

**Comment by Dr-WeiAL** [comment]
> [FCMRIP/HK-Arknights#10 (comment)](https://github.com/FCMRIP/HK-Arknights/issues/10#issuecomment-956311693) 隔壁的结果

意料之中，没办法了(

**Comment by Kamui233** [comment]
好吧，看来是结束了

**Comment by Kamui233** [comment]
那我偷偷藏手机就没jb用了淦

**Comment by Rain0Jack** [comment]
我从16点蹲到现在，人都是麻的

**Comment by Kamui233** [comment]
唉，周五晚上还要考试，又玩不了，怎么就不能保持原来的1.5h呢…

**Comment by Rain0Jack** [comment]
> 唉，周五晚上还要考试，又玩不了，怎么就不能保持原来的1.5h呢…

笑死高中一个月4个小时，玩蛇皮玩，玉都搓不完

**Comment by Kamui233** [comment]
为啥一个月才4h（顺便你是哪个高中🤔）

**Comment by lingranw** [comment]
这种技术属于信息技术里面的哪个领域？网络工程吗

**Comment by Kamui233** [comment]
> 这种技术属于信息技术里面的哪个领域？网络工程吗

不太清楚，咱是一普通高中生，等着大佬救济

**Comment by lingranw** [comment]
> > 这种技术属于信息技术里面的哪个领域？网络工程吗
> 
> 不太清楚，咱是一普通高中生，等着大佬救济

知道github，咱也算见过世面的普通高中生了（

**Comment by lingranw** [comment]
> > > > 这种技术属于信息技术里面的哪个领域？网络工程吗
> > > 
> > > 
> > > 不太清楚，咱是一普通高中生，等着大佬救济
> > 
> > 
> > 知道github，咱也算见过世面的普通高中生了（
> 
> 啊哈哈哈哈这确实，可惜现在都结束了，GitHub也救不了被防沉迷锁死的高中生了qwq

把issue玩成聊天室了属于是，好好念书，进大学研究造福下一代未成年吧（我好像读大学了还没成年，淦

**Comment by yige-yigeren** [comment]
> 隔壁帖子： “现在鹰角让他们的app不走系统代理，可以考虑用ProxyDroid等VPN软件在系统层面强制所有app走代理” “okHttp连接时的参数加了NO_PROXY而已，我用Wireshark仍然可以抓到TLS握手包，怎么可能换协议” 转述一下 我今天就蹲github了（

隔壁帖能指下路吗@.@

**Comment by zhuangjr** [comment]
> > 隔壁帖子： “现在鹰角让他们的app不走系统代理，可以考虑用ProxyDroid等VPN软件在系统层面强制所有app走代理” “okHttp连接时的参数加了NO_PROXY而已，我用Wireshark仍然可以抓到TLS握手包，怎么可能换协议” 转述一下 我今天就蹲github了（
> 
> 隔壁帖能指下路吗@.@

https://github.com/Hawaii-ol/arknights_minor_bypass/issues/10

**Comment by yige-yigeren** [comment]
> > > 隔壁帖子： “现在鹰角让他们的app不走系统代理，可以考虑用ProxyDroid等VPN软件在系统层面强制所有app走代理” “okHttp连接时的参数加了NO_PROXY而已，我用Wireshark仍然可以抓到TLS握手包，怎么可能换协议” 转述一下 我今天就蹲github了（
> > 
> > 
> > 隔壁帖能指下路吗@.@
> 
> [Hawaii-ol/arknights_minor_bypass#10](https://github.com/Hawaii-ol/arknights_minor_bypass/issues/10)

谢谢！

**Comment by yige-yigeren** [comment]
我在此提出一个猜想，
之前网易游戏有通过卡新游戏登录网易账号，先游客登录-绑定账号，这时候实名信息未同步，通过卡登录状态与实名状态不同步的bug，可以覆盖服务器原实名状态的办法。
那么方舟是否可能存在类似漏洞？比如注册接口和实名接口多做测试

**Comment by Dr-WeiAL** [comment]
> 我在此提出一个猜想， 之前网易游戏有通过卡新游戏登录网易账号，先游客登录-绑定账号，这时候实名信息未同步，通过卡登录状态与实名状态不同步的bug，可以覆盖服务器原实名状态的办法。 那么方舟是否可能存在类似漏洞？比如注册接口和实名接口多做测试

你有没有发现方舟现在没有游客登录了

**Comment by Eleven11486** [comment]
有结果踢我，拜托各位大佬了

**Comment by luanmouren** [comment]
> 有结果踢我，拜托各位大佬了

改成服务端认证了，彻底寄了

**Comment by luanmouren** [comment]
日，我的桃子😭

**Comment by Kamui233** [comment]
刚起床，同蹲大佬

**Comment by morettiL** [comment]
刚进校门，有消息踢我一脚

**Comment by YYJ114514** [comment]
大佬们，现在有新的进展吗？

**Comment by Alkaid-Star** [comment]
确切消息，现在还有大佬在努力，晚上等消息吧。

**Comment by Kamui233** [comment]
大佬加油呜

**Comment by Kamui233** [comment]
隔壁贴说基建bug还能用，咱没试过

**Comment by Zheizh** [comment]
基建应该不行，只要yj还在实时监测就躲不了，只能卡在两次监测的间隔

**Comment by Zheizh** [comment]
那也就剩原来的断网大法了 -_-

**Comment by long45343** [comment]
寄了（

**Comment by TLEphage** [comment]
> 那也就剩原来的断网大法了 -_-

我今晚试了一下，断网大法好像用不了qwq

不知道调一下手机上的时间有没有用

**Comment by YYJ114514** [comment]
你们妈的没完了事罢，还来挖坟

**Comment by Dr-WeiAL** [comment]
都多长时间了，还有人发啊，我把这个关了吧（
